// fusion-engine/core/validator/interfaces.ts

/**
 * Defines a single issue found during validation.
 */
export interface ValidationIssue {
  type: 'error' | 'warning'; // Severity of the issue
  message: string;           // Human-readable message
  filePath?: string;         // Optional: Relative path to the file where the issue occurred
  details?: string;          // Optional: More technical details or suggested fixes
  codeSnippet?: string;      // Optional: A relevant code snippet for import issues
}

/**
 * Defines the comprehensive report generated by the validation module.
 */
export interface ValidationReport {
  overallStatus: 'passed' | 'warnings' | 'failed'; // Overall status of the validation process
  issues: ValidationIssue[];                      // All detected issues (errors and warnings)
  summary: {                                      // Aggregated statistics
    totalProjectsValidated: number;
    totalFilesScanned: number;
    criticalErrors: number;
    warnings: number;
    passedChecks: number;
    totalFilesPassed?: number; // ✅ اضافه شد: برای شمارش فایل‌های اسکن شده موفق
  };
}

/**
 * Represents a basic scanned file for validation purposes.
 * This is a lighter version than the one in modules/analyzer.
 */
export interface SimpleScannedFile {
  absolutePath: string;     // Full absolute path
  relativePath: string;     // Path relative to the project root
  fileName: string;         // e.g., 'index.tsx'
  extension: string;        // e.g., '.ts'
}
